//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34003
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Fukami.Entities
{
	[System.Serializable]
	public class ChildSlot{
		public float X = 0.0f;
		public float Y = 0.0f;
		public float Angle = 0.0f;
	    public bool IsOccupied = false;
	}
}

